from __future__ import annotations

from tokensmith.config import TokensmithConfig
from tokensmith.exporters import css, tailwind, typescript
from tokensmith.models import (
    FigmaVariablesResponse,
    Token,
    tokens_from_figma,
)


def _sample_tokens(variables_payload: dict) -> list[Token]:
    response = FigmaVariablesResponse.model_validate(variables_payload)
    return tokens_from_figma(response)


def test_css_export_modes_and_values(variables_payload: dict) -> None:
    tokens = _sample_tokens(variables_payload)
    config = TokensmithConfig(default_mode="Light")
    rendered = css.render(tokens, config)
    contents = rendered["tokens.css"]

    assert ":root {" in contents
    assert '[data-theme="dark"]' in contents
    assert "--color-primary: #2563eb;" in contents
    assert "--spacing-md: 16px;" in contents
    assert "--radius-lg: 12px;" in contents
    assert "--typography-body: Inter;" in contents


def test_css_custom_mode_selectors(variables_payload: dict) -> None:
    tokens = _sample_tokens(variables_payload)
    config = TokensmithConfig(
        default_mode="Light",
        mode_selectors={"Dark": ".dark, [data-mode='dark']"},
    )
    contents = css.render(tokens, config)["tokens.css"]
    assert ".dark, [data-mode='dark']" in contents


def test_tailwind_export_structure(variables_payload: dict) -> None:
    tokens = _sample_tokens(variables_payload)
    config = TokensmithConfig(default_mode="Light")
    contents = tailwind.render(tokens, config)["tailwind.tokens.js"]

    assert "module.exports" in contents
    assert '"color-primary": "#2563eb"' in contents
    assert '"spacing-md": "16px"' in contents
    assert '"borderRadius"' in contents
    assert '"Dark"' in contents


def test_typescript_export_modes(variables_payload: dict) -> None:
    tokens = _sample_tokens(variables_payload)
    config = TokensmithConfig(default_mode="Light")
    contents = typescript.render(tokens, config)["tokens.ts"]

    assert "export const tokensLight" in contents
    assert "export const tokensDark" in contents
    assert "as const" in contents
    assert '"color-primary": "#2563eb"' in contents
    assert "export const tokensByMode" in contents


def test_export_writes_files(tmp_path, variables_payload: dict) -> None:
    tokens = _sample_tokens(variables_payload)
    config = TokensmithConfig(default_mode="Light")
    written = css.export(tokens, config, tmp_path)
    assert written[0].is_file()
    assert "--color-primary:" in written[0].read_text(encoding="utf-8")


def test_empty_tokens_still_render() -> None:
    config = TokensmithConfig()
    assert "Generated by tokensmith" in css.render([], config)["tokens.css"]
    assert "module.exports" in tailwind.render([], config)["tailwind.tokens.js"]
    assert "tokensByMode" in typescript.render([], config)["tokens.ts"]
