"""Export tokens as CSS custom properties."""

from __future__ import annotations

from collections import defaultdict
from pathlib import Path

from tokensmith.config import TokensmithConfig
from tokensmith.models import Token


def render(tokens: list[Token], config: TokensmithConfig) -> dict[str, str]:
    by_mode: dict[str, list[Token]] = defaultdict(list)
    for token in tokens:
        by_mode[token.mode].append(token)

    modes = sorted(by_mode)
    default_mode = _default_mode(modes, config)
    if default_mode in modes:
        modes = [default_mode] + [m for m in modes if m != default_mode]

    blocks: list[str] = [
        "/* Generated by tokensmith — do not edit by hand. */",
        "",
    ]

    for mode in modes:
        selector = _selector_for_mode(mode, default_mode, config)
        lines = [f"{selector} {{"]
        for token in sorted(by_mode[mode], key=lambda t: t.css_name):
            lines.append(f"  --{token.css_name}: {_css_value(token)};")
        lines.append("}")
        blocks.append("\n".join(lines))
        blocks.append("")

    return {"tokens.css": "\n".join(blocks).rstrip() + "\n"}


def export(tokens: list[Token], config: TokensmithConfig, output_dir: Path) -> list[Path]:
    rendered = render(tokens, config)
    written: list[Path] = []
    for filename, contents in rendered.items():
        path = output_dir / filename
        path.write_text(contents, encoding="utf-8")
        written.append(path)
    return written


def _default_mode(modes: list[str], config: TokensmithConfig) -> str | None:
    if config.default_mode and config.default_mode in modes:
        return config.default_mode
    for candidate in ("Light", "light", "Default", "default", "Mode 1"):
        if candidate in modes:
            return candidate
    return modes[0] if modes else None


def _selector_for_mode(mode: str, default_mode: str | None, config: TokensmithConfig) -> str:
    if mode in config.mode_selectors:
        return config.mode_selectors[mode]
    if default_mode is not None and mode == default_mode:
        return ":root"
    slug = mode.lower().replace(" ", "-")
    return f'[data-theme="{slug}"]'


def _css_value(token: Token) -> str:
    value = token.value
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        # Unitless numbers are fine for many tokens; spacing/radius get px.
        if token.category.value in {"spacing", "radius"}:
            return f"{value}px"
        return str(value)
    return str(value)
