"""Export tokens as a Tailwind config partial (CommonJS)."""

from __future__ import annotations

import json
from collections import defaultdict
from pathlib import Path

from tokensmith.config import TokensmithConfig
from tokensmith.models import Token, TokenCategory


def render(tokens: list[Token], config: TokensmithConfig) -> dict[str, str]:
    by_mode: dict[str, list[Token]] = defaultdict(list)
    for token in tokens:
        by_mode[token.mode].append(token)

    modes = sorted(by_mode)
    default_mode = _default_mode(modes, config)

    # Primary export uses the default mode; other modes are nested under `modes`.
    primary = by_mode.get(default_mode or "", []) if default_mode else []
    if not primary and modes:
        primary = by_mode[modes[0]]
        default_mode = modes[0]

    theme = _theme_from_tokens(primary)
    modes_payload = {
        mode: _theme_from_tokens(by_mode[mode])
        for mode in modes
        if mode != default_mode
    }

    payload = {
        "theme": {"extend": theme},
        "modes": modes_payload,
        "meta": {
            "defaultMode": default_mode,
            "generatedBy": "tokensmith",
        },
    }

    body = json.dumps(payload, indent=2, sort_keys=True)
    contents = (
        "/** Generated by tokensmith — do not edit by hand. */\n"
        "/** @type {import('tailwindcss').Config} partial */\n"
        f"module.exports = {body}\n"
    )
    return {"tailwind.tokens.js": contents}


def export(tokens: list[Token], config: TokensmithConfig, output_dir: Path) -> list[Path]:
    rendered = render(tokens, config)
    written: list[Path] = []
    for filename, contents in rendered.items():
        path = output_dir / filename
        path.write_text(contents, encoding="utf-8")
        written.append(path)
    return written


def _default_mode(modes: list[str], config: TokensmithConfig) -> str | None:
    if config.default_mode and config.default_mode in modes:
        return config.default_mode
    for candidate in ("Light", "light", "Default", "default", "Mode 1"):
        if candidate in modes:
            return candidate
    return modes[0] if modes else None


def _theme_from_tokens(tokens: list[Token]) -> dict[str, dict[str, str | int | float]]:
    colors: dict[str, str | int | float] = {}
    spacing: dict[str, str | int | float] = {}
    border_radius: dict[str, str | int | float] = {}
    font_size: dict[str, str | int | float] = {}

    for token in tokens:
        key = token.css_name
        value = _tailwind_value(token)
        if token.category == TokenCategory.COLOR:
            colors[key] = value
        elif token.category == TokenCategory.SPACING:
            spacing[key] = value
        elif token.category == TokenCategory.RADIUS:
            border_radius[key] = value
        elif token.category == TokenCategory.TYPOGRAPHY:
            font_size[key] = value
        else:
            spacing[key] = value

    theme: dict[str, dict[str, str | int | float]] = {}
    if colors:
        theme["colors"] = colors
    if spacing:
        theme["spacing"] = spacing
    if border_radius:
        theme["borderRadius"] = border_radius
    if font_size:
        theme["fontSize"] = font_size
    return theme


def _tailwind_value(token: Token) -> str | int | float:
    value = token.value
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)) and token.category in {
        TokenCategory.SPACING,
        TokenCategory.RADIUS,
    }:
        return f"{value}px"
    return value  # type: ignore[return-value]
