"""Export tokens as a typed TypeScript module."""

from __future__ import annotations

import json
from collections import defaultdict
from pathlib import Path

from tokensmith.config import TokensmithConfig
from tokensmith.models import Token, TokenCategory


def render(tokens: list[Token], config: TokensmithConfig) -> dict[str, str]:
    by_mode: dict[str, list[Token]] = defaultdict(list)
    for token in tokens:
        by_mode[token.mode].append(token)

    modes = sorted(by_mode)
    default_mode = _default_mode(modes, config)

    lines: list[str] = [
        "/* Generated by tokensmith — do not edit by hand. */",
        "",
    ]

    for mode in modes:
        export_name = _export_name(mode, default_mode)
        payload = _group_tokens(by_mode[mode])
        serialized = json.dumps(payload, indent=2, sort_keys=True)
        # json.dumps uses double quotes; valid TS object literal with `as const`.
        type_name = export_name[0].upper() + export_name[1:]
        lines.append(f"export const {export_name} = {serialized} as const;")
        lines.append("")
        lines.append(f"export type {type_name} = typeof {export_name};")
        lines.append("")

    if default_mode and default_mode in by_mode:
        lines.append(f"export const tokens = {_export_name(default_mode, default_mode)};")
        lines.append("")
        lines.append("export type Tokens = typeof tokens;")
        lines.append("")

    all_modes = {mode: _export_name(mode, default_mode) for mode in modes}
    modes_obj = ", ".join(f"{json.dumps(mode)}: {name}" for mode, name in all_modes.items())
    lines.append(f"export const tokensByMode = {{ {modes_obj} }} as const;")
    lines.append("")

    return {"tokens.ts": "\n".join(lines)}


def export(tokens: list[Token], config: TokensmithConfig, output_dir: Path) -> list[Path]:
    rendered = render(tokens, config)
    written: list[Path] = []
    for filename, contents in rendered.items():
        path = output_dir / filename
        path.write_text(contents, encoding="utf-8")
        written.append(path)
    return written


def _default_mode(modes: list[str], config: TokensmithConfig) -> str | None:
    if config.default_mode and config.default_mode in modes:
        return config.default_mode
    for candidate in ("Light", "light", "Default", "default", "Mode 1"):
        if candidate in modes:
            return candidate
    return modes[0] if modes else None


def _export_name(mode: str, default_mode: str | None) -> str:
    if default_mode is not None and mode == default_mode:
        return "tokensLight" if mode.lower() in {"light", "default", "mode 1"} else "tokensDefault"
    slug = "".join(part.capitalize() for part in mode.replace("-", " ").replace("_", " ").split())
    if not slug:
        slug = "Mode"
    if slug[0].isdigit():
        slug = f"Mode{slug}"
    return f"tokens{slug}"


def _group_tokens(tokens: list[Token]) -> dict[str, dict[str, str | int | float | bool]]:
    groups: dict[str, dict[str, str | int | float | bool]] = {
        "color": {},
        "spacing": {},
        "radius": {},
        "typography": {},
        "other": {},
    }
    category_map = {
        TokenCategory.COLOR: "color",
        TokenCategory.SPACING: "spacing",
        TokenCategory.RADIUS: "radius",
        TokenCategory.TYPOGRAPHY: "typography",
        TokenCategory.OTHER: "other",
    }
    for token in tokens:
        group = category_map[token.category]
        groups[group][token.css_name] = token.value

    return {key: value for key, value in groups.items() if value}
